apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp30
  labels:
    app: myapp30
spec:
  selector:
    matchLabels:
      app: myapp30
  template:
    metadata:
      labels:
        app: myapp30
    spec:
      containers:
      - name: myapp30
        image: maximilianou/ui30ci
        ports:
        - containerPort: 3030
