apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp30
  labels:
    app: myapp30
spec:
  selector:
    matchLabels:
      app: myapp30
  template:
    metadata:
      labels:
        app: myapp30
    spec:
      imagePullSecrets:
        - name: my-registry-key
      containers:
      - name: myapp30
#        image: docker.io/maximilianou/ui30ci
        image: maximilianou/ui30ci:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3030
