name: CI Typescript Node.js 
# https://docs.github.com/en/actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd api && npm ci
    - run: cd api && npm run build --if-present
    - run: cd api && npm test
    - name: Build and Push Docker Image
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u maximilianou@gmail.com --password-stdin
        docker build . -t ghcr.io/maximilianou/api30ci:latest
        docker push ghcr.io/maximilianou/api30ci:latest
#  publish:
#    needs: build
#    steps:
#    - 